#!/usr/bin/env ruby
require "optparse"
require_relative "lib/zettacode"

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: zettacode [--parse FILENAME]"

  opts.on("-p", "--parse", "Parse FILENAME") do |p|
    options[:parse] = p
  end
  opts.on("-s", "--scrap", "Scrap RosettaCode URLs") do |s|
    options[:scrap] = s
  end
  opts.on("-v", "--version", "Show version") do |v|
    options[:version] = v
  end
end.parse!

if options == {}
  puts "Usage: zettacode -h"
elsif options[:parse]
  Zettacode::Parse.call(ARGV.first || "NODATA")
elsif options[:scrap]
  scrap = Zettacode::Scrap.new("config/scrap.yaml")
  scrap.load_settings
  scrap.find_langs
elsif options[:version]
  puts "zettacode #{Zettacode::VERSION}"
end
